"""`EpisodicStore` — typed async accessor over the `episodes` table.

One of the three engines surfaced by `charter.memory`. Responsibilities:

- **Append-only writes.** `append_event` is the single ingress point for
  agent-run events that warrant long-term storage; every other engine
  reads through `query_*` accessors.
- **Tenant isolation.** Every query carries `tenant_id` as an explicit
  parameter; the application-side `WHERE tenant_id = ?` is the secondary
  defence on top of Postgres RLS (wired up in Task 7).
- **pgvector-aware ANN.** `search_similar` runs an ivfflat cosine
  distance ranking on Postgres; on aiosqlite (unit tests) it returns
  an empty list rather than raising — calling code can degrade
  gracefully when running in test mode.

Production deployments connect to Postgres via asyncpg; unit tests use
aiosqlite. Both paths go through the same `async_sessionmaker` seam —
the store has no other coupling to the underlying engine.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import desc, select
from sqlalchemy.exc import OperationalError, ProgrammingError
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from charter.memory.models import EpisodeModel


class EpisodeRow:
    """Read-only DTO returned by every `EpisodicStore.query_*` accessor.

    Decouples callers from the SQLAlchemy `EpisodeModel` so the ORM
    layer can evolve without breaking consumers. Constructed only by
    `EpisodicStore._row()`; instances are immutable from a discipline
    perspective (the constructor is the only mutation point).
    """

    __slots__ = (
        "action",
        "agent_id",
        "correlation_id",
        "embedding",
        "emitted_at",
        "episode_id",
        "payload",
        "tenant_id",
    )

    def __init__(
        self,
        *,
        episode_id: int,
        tenant_id: str,
        correlation_id: str,
        agent_id: str,
        action: str,
        payload: dict[str, Any],
        embedding: list[float] | None,
        emitted_at: datetime,
    ) -> None:
        self.episode_id = episode_id
        self.tenant_id = tenant_id
        self.correlation_id = correlation_id
        self.agent_id = agent_id
        self.action = action
        self.payload = payload
        self.embedding = embedding
        self.emitted_at = emitted_at


class EpisodicStore:
    """Typed async accessor over the `episodes` table."""

    def __init__(self, session_factory: async_sessionmaker[AsyncSession]) -> None:
        self._session_factory = session_factory

    async def append_event(
        self,
        *,
        tenant_id: str,
        correlation_id: str,
        agent_id: str,
        action: str,
        payload: dict[str, Any],
        embedding: list[float] | None = None,
    ) -> int:
        """Append a single event. Returns the autogenerated `episode_id`."""
        async with self._session_factory.begin() as session:
            row = EpisodeModel(
                tenant_id=tenant_id,
                correlation_id=correlation_id,
                agent_id=agent_id,
                action=action,
                payload=payload,
                embedding=embedding,
            )
            session.add(row)
            await session.flush()
            return int(row.episode_id)

    async def query_by_correlation_id(
        self,
        *,
        tenant_id: str,
        correlation_id: str,
    ) -> list[EpisodeRow]:
        """Every event for a given correlation_id within the tenant, in
        emit order. Used by D.7 Investigation to walk a delegation chain.
        """
        stmt = (
            select(EpisodeModel)
            .where(
                EpisodeModel.tenant_id == tenant_id,
                EpisodeModel.correlation_id == correlation_id,
            )
            .order_by(EpisodeModel.emitted_at)
        )
        async with self._session_factory() as session:
            result = await session.execute(stmt)
            return [self._row(m) for m in result.scalars().all()]

    async def query_recent(
        self,
        *,
        tenant_id: str,
        limit: int = 100,
    ) -> list[EpisodeRow]:
        """Tenant-scoped descending-emit feed. Backs "what happened today"
        in the operator console.
        """
        stmt = (
            select(EpisodeModel)
            .where(EpisodeModel.tenant_id == tenant_id)
            .order_by(desc(EpisodeModel.emitted_at), desc(EpisodeModel.episode_id))
            .limit(limit)
        )
        async with self._session_factory() as session:
            result = await session.execute(stmt)
            return [self._row(m) for m in result.scalars().all()]

    async def search_similar(
        self,
        *,
        tenant_id: str,
        embedding: list[float],
        top_k: int = 10,
    ) -> list[EpisodeRow]:
        """Approximate-nearest-neighbour search against the embedding column.

        On Postgres: uses pgvector's `<=>` cosine-distance operator
        through the ivfflat index added in the baseline migration.

        On aiosqlite (unit tests): returns [] rather than raising the
        missing-operator error. The live Postgres integration test in
        Task 10 verifies real ANN ranking.
        """
        async with self._session_factory() as session:
            dialect = session.bind.dialect.name if session.bind else ""
            if dialect != "postgresql":
                return []
            try:
                stmt = (
                    select(EpisodeModel)
                    .where(EpisodeModel.tenant_id == tenant_id)
                    .order_by(EpisodeModel.embedding.cosine_distance(embedding))
                    .limit(top_k)
                )
                result = await session.execute(stmt)
                return [self._row(m) for m in result.scalars().all()]
            except (OperationalError, ProgrammingError):
                # Defensive: an installed pgvector but missing index / extension
                # should not crash callers — degrade to empty.
                return []

    @staticmethod
    def _row(model: EpisodeModel) -> EpisodeRow:
        return EpisodeRow(
            episode_id=int(model.episode_id),
            tenant_id=model.tenant_id,
            correlation_id=model.correlation_id,
            agent_id=model.agent_id,
            action=model.action,
            payload=dict(model.payload),
            embedding=list(model.embedding) if model.embedding is not None else None,
            emitted_at=model.emitted_at,
        )


__all__ = ["EpisodeRow", "EpisodicStore"]
