"""`ProceduralStore` — versioned playbook CRUD over the `playbooks` table.

Procedural memory: the "what should we do when X happens" knowledge an
agent (or the remediation pipeline) reads at decision time. Playbooks
are addressed by an LTREE-shaped hierarchical path
(`remediation.s3.public_bucket`, `triage.network.dns_tunnel`, etc.).

Invariants enforced by the store, not the schema:

- **Exactly one active row per `(tenant_id, path)`** at any moment.
  `publish_version` flips the prior active row to `active=False`
  inside the same transaction it inserts the new row.
- **Monotonically increasing versions** per `(tenant_id, path)`,
  starting at 1. Older versions are retained (not deleted) so the
  audit + rollback path stays open.
- **Tenant isolation** on every read path.

LTREE subtree containment (`<@`) is Postgres-only. On aiosqlite the
column is a `String(512)` and `list_subtree` falls back to a prefix
`LIKE` match. Both implementations satisfy the same semantics:
`list_subtree(prefix="a.b")` returns rows where `path == "a.b"` OR
`path` is a descendant of `a.b` under the LTREE dot-separated taxonomy.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import ColumnElement, desc, func, select, update
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from charter.memory.models import PlaybookModel


class PlaybookRow:
    """Read-only DTO returned by `ProceduralStore.*`."""

    __slots__ = (
        "active",
        "body",
        "path",
        "playbook_id",
        "published_at",
        "tenant_id",
        "version",
    )

    def __init__(
        self,
        *,
        playbook_id: int,
        tenant_id: str,
        path: str,
        version: int,
        active: bool,
        body: dict[str, Any],
        published_at: datetime,
    ) -> None:
        self.playbook_id = playbook_id
        self.tenant_id = tenant_id
        self.path = path
        self.version = version
        self.active = active
        self.body = body
        self.published_at = published_at


class ProceduralStore:
    """Typed async accessor over the `playbooks` table."""

    def __init__(self, session_factory: async_sessionmaker[AsyncSession]) -> None:
        self._session_factory = session_factory

    async def publish_version(
        self,
        *,
        tenant_id: str,
        path: str,
        body: dict[str, Any],
    ) -> int:
        """Insert a new version of `path` as the new active row.

        Returns the autogenerated `version` (1-based, monotonic within
        `(tenant_id, path)`). The prior active row, if any, is flipped
        to `active=False` in the same transaction.
        """
        async with self._session_factory.begin() as session:
            # 1. Compute the next version.
            current_max = await session.scalar(
                select(func.coalesce(func.max(PlaybookModel.version), 0)).where(
                    PlaybookModel.tenant_id == tenant_id,
                    PlaybookModel.path == path,
                )
            )
            next_version = int(current_max or 0) + 1

            # 2. Deactivate any prior active row for this (tenant, path).
            if next_version > 1:
                await session.execute(
                    update(PlaybookModel)
                    .where(
                        PlaybookModel.tenant_id == tenant_id,
                        PlaybookModel.path == path,
                        PlaybookModel.active.is_(True),
                    )
                    .values(active=False)
                )

            # 3. Insert the new active row.
            row = PlaybookModel(
                tenant_id=tenant_id,
                path=path,
                version=next_version,
                active=True,
                body=body,
            )
            session.add(row)
            await session.flush()
            return next_version

    async def get_active(
        self,
        *,
        tenant_id: str,
        path: str,
    ) -> PlaybookRow | None:
        """Return the active version of `path`, or `None` if never published."""
        stmt = select(PlaybookModel).where(
            PlaybookModel.tenant_id == tenant_id,
            PlaybookModel.path == path,
            PlaybookModel.active.is_(True),
        )
        async with self._session_factory() as session:
            model = (await session.execute(stmt)).scalar_one_or_none()
            return self._row(model) if model is not None else None

    async def list_versions(
        self,
        *,
        tenant_id: str,
        path: str,
    ) -> list[PlaybookRow]:
        """Return every version for `(tenant_id, path)`, newest first."""
        stmt = (
            select(PlaybookModel)
            .where(
                PlaybookModel.tenant_id == tenant_id,
                PlaybookModel.path == path,
            )
            .order_by(desc(PlaybookModel.version))
        )
        async with self._session_factory() as session:
            return [self._row(m) for m in (await session.execute(stmt)).scalars().all()]

    async def list_subtree(
        self,
        *,
        tenant_id: str,
        prefix: str,
    ) -> list[PlaybookRow]:
        """Return every active playbook whose path is `prefix` or a descendant.

        Postgres: `path <@ prefix::ltree`. Other dialects: `path = prefix`
        OR `path LIKE prefix || '.%'` — same semantics for the LTREE
        dot-taxonomy that v0.1 uses.
        """
        async with self._session_factory() as session:
            dialect = session.bind.dialect.name if session.bind else ""
            where_clause: ColumnElement[bool]
            if dialect == "postgresql":
                where_clause = PlaybookModel.path.op("<@")(prefix)
            else:
                where_clause = (PlaybookModel.path == prefix) | PlaybookModel.path.like(
                    f"{prefix}.%"
                )
            stmt = (
                select(PlaybookModel)
                .where(
                    PlaybookModel.tenant_id == tenant_id,
                    PlaybookModel.active.is_(True),
                    where_clause,
                )
                .order_by(PlaybookModel.path)
            )
            return [self._row(m) for m in (await session.execute(stmt)).scalars().all()]

    @staticmethod
    def _row(model: PlaybookModel) -> PlaybookRow:
        return PlaybookRow(
            playbook_id=int(model.playbook_id),
            tenant_id=model.tenant_id,
            path=model.path,
            version=int(model.version),
            active=bool(model.active),
            body=dict(model.body),
            published_at=model.published_at,
        )


__all__ = ["PlaybookRow", "ProceduralStore"]
